// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: film.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FilmHandler_GetAllFilms_FullMethodName = "/v1.FilmHandler/GetAllFilms"
)

// FilmHandlerClient is the client API for FilmHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FilmHandlerClient interface {
	GetAllFilms(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListFilmResponse, error)
}

type filmHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewFilmHandlerClient(cc grpc.ClientConnInterface) FilmHandlerClient {
	return &filmHandlerClient{cc}
}

func (c *filmHandlerClient) GetAllFilms(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListFilmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFilmResponse)
	err := c.cc.Invoke(ctx, FilmHandler_GetAllFilms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FilmHandlerServer is the server API for FilmHandler service.
// All implementations must embed UnimplementedFilmHandlerServer
// for forward compatibility.
type FilmHandlerServer interface {
	GetAllFilms(context.Context, *Empty) (*ListFilmResponse, error)
	mustEmbedUnimplementedFilmHandlerServer()
}

// UnimplementedFilmHandlerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFilmHandlerServer struct{}

func (UnimplementedFilmHandlerServer) GetAllFilms(context.Context, *Empty) (*ListFilmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllFilms not implemented")
}
func (UnimplementedFilmHandlerServer) mustEmbedUnimplementedFilmHandlerServer() {}
func (UnimplementedFilmHandlerServer) testEmbeddedByValue()                     {}

// UnsafeFilmHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FilmHandlerServer will
// result in compilation errors.
type UnsafeFilmHandlerServer interface {
	mustEmbedUnimplementedFilmHandlerServer()
}

func RegisterFilmHandlerServer(s grpc.ServiceRegistrar, srv FilmHandlerServer) {
	// If the following call pancis, it indicates UnimplementedFilmHandlerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FilmHandler_ServiceDesc, srv)
}

func _FilmHandler_GetAllFilms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilmHandlerServer).GetAllFilms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilmHandler_GetAllFilms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilmHandlerServer).GetAllFilms(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// FilmHandler_ServiceDesc is the grpc.ServiceDesc for FilmHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FilmHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.FilmHandler",
	HandlerType: (*FilmHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllFilms",
			Handler:    _FilmHandler_GetAllFilms_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "film.proto",
}
